openapi: "3.0.0"
info:
  version: 1.0.0
  title: 百度搜索 API
  license:
    name: MIT
servers:
  - url: http://baidu.com
paths:
  /s:
    get:
      summary: baidu search
      operationId: baidu_search
      tags:
        - search
      parameters:
        - name: wd
          in: query
          description: 查询关键词
          required: true
          schema:
            type: string
        - name: tn
          in: query
          description: 返回结果的格式（json）
          required: false
          schema:
            type: string
            default: json
        - name: rn
          in: query
          description: 返回结果的个数
          required: false
          schema:
            type: integer
            default: 10
        - name: ie
          in: query
          description: 返回结果的格式
          required: false
          schema:
            type: string
            default: utf-8
      responses:
        "200":
          description: 搜索结果
          content:
            application/json:
              schema:
                type: object
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
